import type { Metadata } from 'next'
import { Inter,Poppins } from 'next/font/google'
import '../style/globals.css'

const inter = Poppins({subsets:['latin'],weight:'400'})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html dir='rtl' lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
